### ISSUE TITLE
jsonパーサーのライブラリが欲しい

### ISSUE THREAD

**Issue by jojonki** [montblancpj/unity-lego-game#1]
Arduinoのシリアルポートの設定をコードでなく外出しのjsonファイルにしたいので、Unityで使える何らかのjsonパーサーの追加をお願いします。
パーサーはなんでも良いです。

**Comment by hecomi** [comment]
帰ったらやります。

**Comment by hecomi** [comment]
`Utilities.ReadJSON` を追加しました。
詳しくは `Assets/Scene/Samples/ReadJson.unity` を見て下さい。
