### ISSUE TITLE
位置キャリブを簡単にしたい

### ISSUE THREAD

**Issue by hecomi** [montblancpj/unity-lego-game#2]
映像の位置合わせを簡単にしたい。

恐らく以下の機能で行けるのではないかと考えている：
- カメラは中心を `LookAt`
- 十字キーでカメラ移動
- `PageDown` / `PageUp` で FOV 変更

**Comment by hecomi** [comment]
@jojonki >
作業しました。以下の機能になってます。
- `F1` : キャリブ終了
- `F2` : 位置
- `F3` : 角度
- `F4` : スケール
  台形補正は角度 + 位置の調整で可能です。

**Comment by jojonki** [comment]
あざっす！
