### ISSUE TITLE
背景差し替え

### ISSUE THREAD

**Issue by hecomi** [montblancpj/unity-lego-game#6]
現状の背景はプロジェクタ投影時に見辛いので色を変える、出来高でキーで差し替え出来るようにする

**Comment by hecomi** [comment]
元データ、イラレでモリモリやってた気がするけどどっか言っちゃった気がするので適当に調整します。

**Comment by hecomi** [comment]
手抜きした、どぎついかな...

![2014-08-17 14 05 15](https://cloud.githubusercontent.com/assets/493433/3943820/1fad1546-25cc-11e4-95e8-5b6ec3bd955d.png)

**Comment by hecomi** [comment]
オリジナルはコレ
![2014-08-17 14 06 29](https://cloud.githubusercontent.com/assets/493433/3943823/49ea5ca6-25cc-11e4-96fc-1f89cf893697.png)

**Comment by hecomi** [comment]
彩度上げ版
![2014-08-17 14 07 26](https://cloud.githubusercontent.com/assets/493433/3943824/6b1a2b0e-25cc-11e4-8ab0-163dad4c9c6d.png)

**Comment by hecomi** [comment]
シンプル化
![2014-08-17 14 10 43](https://cloud.githubusercontent.com/assets/493433/3943832/e3e0e618-25cc-11e4-9168-3c8489e5ce68.png)

**Comment by hecomi** [comment]
レゴに投影するとどうせディテール見えないしシンプル方向でいいな

**Comment by hecomi** [comment]
うーん...
![2014-08-17 14 24 42](https://cloud.githubusercontent.com/assets/493433/3943855/d9590c00-25ce-11e4-9698-9c8743d97fda.png)

**Comment by jojonki** [comment]
実際に写して見ると印象変わりそうだから、実際に写してみますか。
何となくポップな感じにしておいたほうが子供受けも良さそう。赤は怖い感じ与えないかちょい不安。でもまぁクッパ城とかこんな感じか。

**Comment by hecomi** [comment]
何かベース欲しいな。上の工場、某アレは空と地下みたいに。

**Comment by hecomi** [comment]
キャラ３色とかでも良いな。

**Comment by hecomi** [comment]
単色
![2014-08-17 17 57 17](https://cloud.githubusercontent.com/assets/493433/3944129/874eb964-25ec-11e4-8388-bc2bd206e227.png)

**Comment by hecomi** [comment]
ブロック色変更
![2014-08-17 18 00 51](https://cloud.githubusercontent.com/assets/493433/3944133/06ffbeec-25ed-11e4-86e5-4b858b804405.png)

**Comment by hecomi** [comment]
やっぱり世界観欲しいから工場テイストで。

![2014-08-17 18 23 50](https://cloud.githubusercontent.com/assets/493433/3944184/44926c7a-25f0-11e4-8fa7-ee3aff033d6f.png)

**Comment by hecomi** [comment]
これかな、取り敢えず全体的に色上げてコントラストだけ上げた。

**Comment by jojonki** [comment]
いいね。映すと意外と上下で差が出なそうな気もするのでそこは調整しましょう。
あとやっぱりステージ上の横長のライト？がステージ上、なにか意味のあるものに見えなくもない。もうちょっと存在感消しても良いかも

**Comment by hecomi** [comment]
ライト L キーで ON/OFF 出来るようにした。でも絵に書き込んであるのは消せない。
![2014-08-17 18 36 44](https://cloud.githubusercontent.com/assets/493433/3944213/0994bb58-25f2-11e4-9120-41db1915635d.png)

**Comment by hecomi** [comment]
関係ないけどブロックぶっ壊したときのタートルズ感良かった（プロジェクションすると微妙かもだけど）
![2014-08-17 18 31 04](https://cloud.githubusercontent.com/assets/493433/3944216/2e3b24ce-25f2-11e4-8260-1f673cb0b1a3.png)

**Comment by jojonki** [comment]
乙した 🍺
